version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    #you can specify any port that your browser want to use
    ports:
        - '3050:80'

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWord=postgres_password

  redis:
    image: 'redis:latest'

  api: 
    build:
    #following lines menas inside server folder, fine docker file Dockerfile.dev
      dockerfile: Dockerfile.dev
      context: ./server
      #make sure it is volumes, not volume, otherwise you will get error
      #when run docker-compose up command
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
    #host value is service name
      - REDIS_HOST=redis
      # default port
      - REDIS_PORT=6379
      #use postgrets default info
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
      
  worker:
      build:
          dockerfile: Dockerfile.dev
          context: ./worker
      volumes:
        - /app/node_modeule
        - .worker:/app
      
